terminado/management.py
terminado/websocket.py

This should mitigate #4
@payne92, do you have time to install this branch and test it out with IPython? It should ensure that at least the most recent prompt is always shown when a new client is connected.

Buffer the last 10 reads from the pty, and play back to new clients

---

terminado/tests/basic_test.py

Hopefully this is enough of a read timeout for Travis

More liberal read time out to address Travis CI test issues

---

terminado/management.py
terminado/tests/basic_test.py
terminado/websocket.py

Typo fix for MaxTerminalsReached exception
Handle cases where TermSocket.terminal not fully initialized

Fix bugs when max_terminals reached, with test cases

---

setup.cfg

Terminado currently doesn't have wheels on pypi. This patch makes uploaded wheels universal (one wheel for python 2 and 3).

Make built wheels universal.

---

terminado/websocket.py

Avoid conflicts with tornado.RequestHandler._log.
Fixes takluyver/terminado#18

Change _log -> _logger.

---

terminado/websocket.py

when overriding the method
ensures behavior is consistent across tornado versions

use tornado's check_origin method name

---

terminado/management.py

@ellisonbg, I haven't got round to trying to reproduce the issue on your server, but I think I may have found one possible cause. If you have time, can you try installing from this branch and see if you can still reproduce the issue?

Close PtyProcess object instead of closing fd directly

---

terminado/websocket.py

I use nginx as a reverse proxy in front of terminado and jupyter. One issue I am having is that after there is no activity in the web terminal window for more than 60 seconds (default timeout in nginx), nginx will close the connection. This pull request is to add a feature to terminado to perodically send websocket "ping" frames when there is no activity. For example, if we set the keep_alive_time to 5 seconds, we will send a "ping" message when there is no activity for more than 5 seconds, No ping message will be sent when there is activity to conserve bandwidth.

 keep websocket connection alive by sending pings when there is no activity

---

terminado/websocket.py

This should allow terminals in Jupyter to use the websocket pinging implemented by a mixin class.
Ping @minrk @zyzhu2000

Revert pinging implementation, and call super method in websocket open

---

MANIFEST.in

The PyPI tarball is missing a license file, please add it.

Include LICENSE.txt file in the tarball

---

terminado/management.py

Closes gh-37
@sknepal could you try this out and see if it fixes your issue with firejail?

Send SIGHUP to the process group in the terminal, not just the leader

---

terminado/management.py

`NamedTermManager.kill` takes a signal as a keyword argument but doesn't pass it through to `PtyWithClients.kill`, which looks like an oversight.

Pass signal to terminal from manager method

---

.gitignore
appveyor.yml
pyproject.toml
terminado/management.py
terminado/tests/basic_test.py

Relies on https://github.com/spyder-ide/pywinpty/pull/67 and a release.
Note this is for Python 3 only because `pywinpty` does not support Python 2.
Here's a screenshot with ``` export SHELL=`which cmd` ```:
Here it is with ``` export SHELL=`which bash` ```:
Passing build on https://ci.appveyor.com/project/blink1073/terminado/build/1.0.7
I can take care of any Windows related maintenance issues moving forward.

Add support for Windows

---

terminado/websocket.py

This fixes an error I was seeing when exiting a terminal which is open in multiple tabs at the same time. The code path to resize the terminal to the smallest client window size was taken, which tries to communicate with the (now closed) terminal:
```
[E 10:17:30.026 NotebookApp] Uncaught exception GET /terminals/websocket/1 (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/terminals/websocket/1', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
File "/home/takluyver/.local/lib/python3.6/site-packages/tornado/web.py", line 1499, in _stack_context_handle_exception
raise_exc_info((type, value, traceback))
File "<string>", line 4, in raise_exc_info
File "/home/takluyver/.local/lib/python3.6/site-packages/tornado/stack_contex …
```

Set websocket.terminal to None when the child exits

---

terminado/management.py

Jupyter brings in latest tornado version 6.0.1 and it breaks Jupyter Terminal due to removing
of gen.Task in earlier version, https://www.tornadoweb.org/en/stable/releases/v6.0.0.html

Fix for https://github.com/jupyter/terminado/issues/62

---

pyproject.toml

Based on the versions tested by .travis.yml, which match the supported CPython versions.
https://en.wikipedia.org/wiki/CPython#Version_history
And here's the pip installs for terminado from PyPI for May 2018:
| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  41.87% |        136,449 |
| 3.6            |  26.07% |         84,967 |
| 3.5            |  18.60% |         60,618 |
| 3.4            |  13.15% |         42,869 |
| 3.7            |   0.27% |            876 |
| 3.3            |   0.03% |            103 |
| 2.6            |   0.00% |             15 |
| 3.8            |   0.00% |              1 |
| Total          |         |        325,898 |
Source: `pypinfo --start-date 2018-05-01 --end-date 2018-05-31 --percent --markdown …

Add python_requires to help pip, and version classifers

---

.travis.yml
terminado/management.py

Hi, I am trying to fix this issue jupyterlab/jupyterlab#1366 in jupyterlab so that terminals open in the current working directory. 
In order to do this, we need to be able to pass key word arguments to the `new_terminal` call in `new_named_terminal` so that the jupyter server can create terminals with different working directories.
https://github.com/jupyter/terminado/blob/b0b32f3efdde4252466f4e57b98773d9e86951ec/terminado/management.py#L317-L324

Add kwargs to NamedTermManager.new_named_terminal

---

.travis.yml
appveyor.yml
pyproject.toml
terminado/tests/basic_test.py

Python 2 and 3.4 have reached EOL, and 3.5 will soon reach EOL.

Drop python 2 and 3.4 and 3.5 support

---

MANIFEST.in

#83 problem could be solved adding the js files through the manifest. The `sdist` package contains all the files needed after this commit.

Add js files in package manifest

---

terminado/management.py

When spawning individual servers in a way that has systemd as an ancestor somewhere up the process tree (e.g. using `SystemdSpawner`), the server inherits systemd's default of [ignoring SIGPIPE](https://lists.freedesktop.org/archives/systemd-devel/2014-August/021982.html). This in turn means that if you start a terminal inside the individual server and run pipelines, you can come across `Broken pipe` errors which you wouldn't normally see in an interactive shell that has default SIGPIPE handling:
```sh
user@host:~/ls20-21$ yes | head
y
y
y
y
y
y
y
y
y
y
yes: standard output: Broken pipe
```
(See [this post on the Jupyter Discourse](https://discourse.jupyter.org/t/unexpected-broken-pipe-errors-in-the-jupyterlab-terminal/8297) for more details.)
The systemd-devel mailing list post linked in …

Make sure SIGPIPE has default handler set

---

terminado/management.py

Allow non-strict decode for process output

---

terminado/management.py

grab current reference as needed
improves compatibility with current tornado, avoids stale handles if IOLoop changes
between instantiation and starting events

avoid persistent handle on IOLoop instance

---

.github/workflows/test.yml
setup.py
terminado/__init__.py
terminado/tests/basic_test.py

Fixes https://github.com/jupyter/terminado/issues/97

PR: Pin pywinpty version to 1.1.0

---

terminado/management.py

related issue: #106 
It seems that sometimes if there is no data ready, it will also trigger the execution of this function, and blocking the entire main thread. This phenomenon is very similar to a deadlock, so another judgment is added to ptyread to avoid this situation.

Fix blocking of pty_read when there isn't pty data ready to read

---

terminado/management.py

This fixes https://github.com/jupyter/terminado/issues/110

Switch select() to poll() in pty_read()

---

.github/workflows/test.yml
terminado/tests/basic_test.py

* Expand test matrix to include all supported versions except pypy on Windows which lacks a published wheel for pywinpty and results in an install failure
* Retry failed tests
* Skip flaky max_terminals tests on all platforms but Linux

Clean up tests

---

terminado/tests/basic_test.py

https://docs.python.org/3/library/unittest.html#deprecated-aliases

Replace deprecated unittest aliases

---

terminado/management.py

fix for https://github.com/jupyterlab/jupyterlab/issues/3413, explanation of the fixes is on the issue.
* the default TERM to xterm-256color
* only override TERM if its not previously set

correctly set the TERM variable

---

terminado/management.py

fix for: https://github.com/jupyterlab/jupyterlab/issues/3413#issuecomment-914293421
the issue is that if the user starts jupyerlab from the terminal, the TERM would be picked up by terminado, which is not right as the parent terminal of the user could be very different.
terminado should be the only one setting the term variable.

Revert "only override TERM if its not previously set"

---

CHANGELOG.md

Automated Changelog Entry for 0.12.2 on main
| Since | 0.12.1 |

Automated Changelog Entry for 0.12.2 on main

---

terminado/tests/basic_test.py
terminado/websocket.py

Resolve #121 (terminal output logging type error) by refactoring message content checks.
Move `LOG_TERMINAL_OUTPUT` env variable check into initialize, and check flag before preparing messages to send for performance.
Fix `PytestCollectionWarning: cannot collect test class 'TestTermClient'` due to incorrect test discovery.

Fix terminal output logging type error

---

CHANGELOG.md

Automated Changelog Entry for 0.12.3 on main
| Since | v0.12.2 |

Automated Changelog Entry for 0.12.3 on main

---

setup.cfg

not metadata, where it's being ignored.
As a result, terminado 0.13 lacks the python_requires metadata, and will be selected for installation on old, incompatible Pythons.
[ref](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html)

python_requires is an option in setup.cfg

---

CHANGELOG.md

Automated Changelog Entry for 0.13.1 on main
| Since | v0.13.0 |

Automated Changelog Entry for 0.13.1 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.13.2 on main
| Since | v0.13.1 |

Automated Changelog Entry for 0.13.2 on main

---

CHANGELOG.md

Automated Changelog Entry for 0.13.3 on main
| Since | v0.13.2 |

Automated Changelog Entry for 0.13.3 on main

---

terminado/management.py

allow passing extra env vars when a new terminal is created

---

pyproject.toml

Use the newly available pypa build backend, which gives us more flexibility.

Switch to hatch backend

---

.github/workflows/test.yml
demos/custom_exec.py
terminado/management.py
terminado/tests/basic_test.py
terminado/websocket.py

A fix for #183 
This includes switching to using a dedicated executor for blocking IO, specifically wrapping calls to ptyprocess.write which, can hang when the PTY buffer (the size of which is set by the OS) is exceeded. TermSocket users can provide their own thread pool by using the named `blocking_io_executor` parameter on initialization, but by default a shared, process-wide single threaded executor will be used.
This also includes a regression test which will fail on Debian and OSX (but may be able to pass on some OSs due to the variance of the PTY buffer's size).
This also switched the default filetype of terminado/tests/basic_test.py from dos to unix to match with the rest of the files in this package and prevent some editors from auto-inserting carriage returns on save.

Fix issue where large stdin writes can cause Tornado to hang

---

CHANGELOG.md

Automated Changelog Entry for 0.16.0 on main
| Draft Release | https://github.com/jupyter/terminado/releases/tag/untagged-432eba51f9a2ef82099d  |
| Since | v0.15.0 |

Automated Changelog Entry for 0.16.0 on main

---

.github/workflows/check-release.yml
.github/workflows/test.yml
.pre-commit-config.yaml
pyproject.toml

- Remove prettier and add pyproject validation and mdformat
- Use releaser v2
- Bump pytest dep to fix min version test
- Ignore warnings in prerelease and min version test
- Use new pre-commit action in maintainer-tools

Maintenance cleanup

---

terminado/tests/basic_test.py

Use splitlines() instead of manually splitting on \r or  \n. Use the first line that looks like a PID (all numbers, as re.match only looks at the start of the line and the regex only allows numbers until end of line anchor).
Fixes https://github.com/jupyter/terminado/issues/84

Don't split manually on linebreaks

---

.github/workflows/test.yml
README.md
codecov.yml
pyproject.toml

cf https://github.com/jupyterlab/maintainer-tools/pull/189

Use local coverage
